name: smart_ms3
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_blue: ^0.7.2
  clay_containers: ^0.2.2
  oscilloscope: ^0.0.3
  cloud_firestore: ^0.13.6
  date_time_format: ^1.0.0+4
  fl_chart: ^0.10.0
  firebase_auth: ^0.16.1
  provider: ^4.1.3
  auto_size_text: ^2.1.0
  flutter_rounded_progress_bar: 0.1.1
  intl: ^0.16.1
  flutter_form_builder: ^3.11.4



dev_dependencies:
  flutter_test:
    sdk: flutter




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/icon1.png
    - assets/icons/icon2.png
    - assets/icons/icon3.png
    - assets/icons/icon4.png
    - assets/icons/chest.png
    - assets/icons/deltoid.jpg
    - assets/icons/trapezius.jpg
    - assets/icons/serratus.jpg
    - assets/icons/teres.png
    - assets/icons/pecs.png
    - assets/icons/dorsi.png
    - assets/icons/supraspinatus.png
    - assets/icons/subscapularis.png
    - assets/icons/infraspinatus.png
    - assets/icons/rhomboid.png




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: assets/HelveticaNeue.ttf
    - family: Ikaros
      fonts:
        - asset: assets/Ikaros-Regular.otf
    - family: LondrinaOutline
      fonts:
        - asset: assets/LondrinaOutline-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
